Condensed stats of zimcheck data
openzim/cms pull request #95
Opened 2023-01-23 10:53 UTC by fadiga

Close #78

2023-01-25 11:45 UTC, rgaudin requested changes
Please check inline comments ; haven't looked at the tests yet

2023-01-25 11:45 UTC, rgaudin commented on frontend/src/views/ZimcheckDashboard.vue
> +        parent.checkTotals = response.data.checkTotals
Here's a hint on how to get a single, scraper-aware dict from the API as well as having an extendable list of checks

```js
        // list of known check we want to display values for (can be extended)
        const knownChecks = new Map([
          ['checksum', 'error'],
          ['integrity', 'error'],
          ['empty', 'error'],
          ['metadata', 'error'],
          ['favicon', 'error'],
          ['main_page', 'error'],
          ['redundant', 'warning'],
          ['url_internal', 'error'],
          ['url_external', 'error'],
          ['redirect', 'error']
        ])

        parent.checkTotals = new Map()
        knownChecks.forEach((value, key) => parent.checkTotals.set(key, 0))

        parent.scraperData = response.data.checkData
        for (const data of Object.values(scraperData)) {
          for (const [check, value] of Object.entries(data)) {
            parent.checkTotals.set(check, (parent.checkTotals.get(check) || 0) + value)
          }
        }
```

2023-01-27 14:58 UTC, fadiga commented on backend/src/backend/routes/zimcheck_dashboard.py
> +                .exclude_fields(["title", "counter", "languages", "tags"])
These are the fields that can be excluded without causing any issues.

2023-01-27 17:52 UTC, rgaudin requested changes
Almost ready to merge. Please check the comment regarding the test

2023-01-27 17:52 UTC, rgaudin commented on backend/tests/test_zimcheck_dashboard.py
> +    book_dict["zimcheck"].update(
We want this in a fixture so it's centralized.

2023-01-27 17:52 UTC, rgaudin commented on backend/tests/test_zimcheck_dashboard.py
> +    assert response.json() == {"checkData": {"": {"redundant": 2}}}
Please also test one with a Scraper metadata

2023-01-27 19:39 UTC, rgaudin approved these changes
LGTM

2023-01-27 19:40 UTC, merged